import { Component } from '@angular/core';
import { DatosService } from '../../services/datos.service';

@Component({
  selector: 'app-form',
  standalone: true,
  imports: [],
  templateUrl: './form.component.html',
  styleUrl: './form.component.css'
})
export class FormComponent {

  private result:string = '';
  private palabras:string[] = [
    "Lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet,",
    "consectetur",
    "adipiscing",
    "elit.",
    "Curabitur",
    "fringilla,",
    "tortor",
    "non",
    "consequat",
    "luctus,",
    "urna",
    "lorem",
    "porta",
    "nibh,",
    "quis",
    "dictum",
    "dui",
    "tellus",
    "sit",
    "amet",
    "ex.",
    "Quisque",
    "ornare",
    "vehicula",
    "justo,",
    "nec",
    "lobortis",
    "tellus",
    "elementum",
    "a.",
    "Curabitur",
    "a",
    "pellentesque",
    "enim,",
    "sed",
    "ultrices",
    "tellus.",
    "Pellentesque",
    "id",
    "neque",
    "at",
    "massa",
    "ornare",
    "ultricies.",
    "Phasellus",
    "eu",
    "purus",
    "a",
    "urna",
    "vulputate",
    "egestas.",
    "Etiam",
    "feugiat",
    "tristique",
    "luctus.",
    "Quisque",
    "et",
    "eros",
    "nisl.",
    "Duis",
    "iaculis",
    "justo",
    "ut",
    "tellus",
    "vehicula,",
    "sit",
    "amet",
    "molestie",
    "diam",
    "iaculis.",
    "Nam",
    "quis",
    "tortor",
    "sollicitudin,",
    "luctus",
    "risus",
    "quis,",
    "egestas",
    "ipsum.",
    "Aenean",
    "aliquet",
    "sollicitudin",
    "quam",
    "vel",
    "pharetra.",
    "Donec",
    "auctor,",
    "diam",
    "sit",
    "amet",
    "tristique",
    "malesuada,",
    "lacus",
    "velit",
    "feugiat",
    "felis,",
    "vitae",
    "tincidunt",
    "mauris",
    "felis",
    "sit",
    "amet",
    "mi.",
    "Integer",
    "vitae",
    "rutrum",
    "velit.",
    "Nam",
    "et",
    "diam",
    "quam.",
    "Nunc",
    "tempor,",
    "ex",
    "a",
    "posuere",
    "rutrum,",
    "massa",
    "sapien",
    "finibus",
    "est,",
    "ut",
    "venenatis",
    "elit",
    "mi",
    "id",
    "augue.",
    "Mauris",
    "convallis",
    "in",
    "libero",
    "et",
    "scelerisque.",
    "Curabitur",
    "blandit,",
    "odio",
    "eu",
    "euismod",
    "mattis,",
    "orci",
    "elit",
    "gravida",
    "purus,",
    "eget",
    "tempus",
    "dolor",
    "massa",
    "sed",
    "nibh."]

  numLorem(value:string){
    
    this.result = '';


      for (let index = 0; index < parseInt(value); index++) {
          this.result+=this.palabras[Math.floor(Math.random() * (50 - 0) + 0)]+' ';
      }

      this.datosService.set_lorem(this.result);
  }

  constructor(
    private datosService:DatosService
  ) { }

}
